apiVersion: apps/v1
kind: Deployment
metadata:
  name: minestom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minestom
  template:
    metadata:
      labels:
        app: minestom
    spec:
      containers:
        - name: minestom
          image: minestomstuff:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 25565
---
apiVersion: v1
kind: Service
metadata:
  name: minestom-svc
spec:
  type: NodePort
  selector:
    app: minestom
  ports:
    - name: mc
      port: 25565
      targetPort: 25565
